name: MultiTNT
main: dktapps\MultiTNT\Main
version: 0.0.1
api: 4.0.0
load: POSTWORLD
author: dktapps
website: https://github.com/dktapps-pm-pl/MultiTNT
description: Ignite all connected TNT at once when lighting one block
